routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear-cache', function() {
    $run = Artisan::call('config:clear');
    $run = Artisan::call('cache:clear');
    $run = Artisan::call('config:cache');
    return 'FINISHED';  
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



/*
|--------------------------------------------------------------------------
|-------------------------- ---Admin Routes--- ----------------------------
|--------------------------------------------------------------------------
*/


//Auth
Route::group( ['prefix' => 'admin', 'as' => 'admin.'], function() {

    //Authorization
    Route::get('/login','Backend\Auth\AdminAuthController@showLoginForm')->name('login');
    
    Route::post('/login', 'Backend\Auth\AdminAuthController@login')->name('login.submit');
    Route::get('logout/', 'Backend\Auth\AdminAuthController@logout')->name('logout');

    // Password Reset
    Route::get('/password/reset','Backend\Auth\AdminAuthController@showLinkRequestForm')
    ->name('password.request');
    Route::post('/password/email','Backend\Auth\ResetPasswordController@sendResetLinkEmail')
    ->name('password.email');

    Route::get('/password/reset/{token}', 'Backend\Auth\ResetPasswordController@showResetForm')
    ->name('password.reset');
    Route::post('/password/reset', 'Backend\Auth\ResetPasswordController@reset')
        ->name('password.update');


    //Dashboard
    Route::get('/', 'Backend\AdminController@index')->name('dashboard');




    // ********Functionalities*********

    //Admin
    Route::get('admin/create', 'Backend\AdminController@createAdmin')->name('admin.create');
    Route::post('admin/create', 'Backend\AdminController@storeAdmin')->name('admin.create.submit');
    Route::post('admin/ban', 'Backend\AdminController@adminBan');
    Route::get('admin/update/{id}', 'Backend\AdminController@editAdmin')->name('admin.update');
    Route::post('admin/update/{id}', 'Backend\AdminController@updateAdmin')->name('admin.update.submit');
    Route::get('admins', 'Backend\AdminController@admins')->name('admins');
    Route::get('profile/{username}', 'Backend\AdminController@profile')->name('profile');
    Route::get('profile', 'Backend\AdminController@show')->name('profile.own');
    Route::post('profile/update', 'Backend\AdminController@update');
    Route::get('admin/delete/{id}', 'Backend\AdminController@destroy')->name('admin.delete');
   


    //User
    Route::post('user/create', 'Backend\AdminController@userCreate')->name('user.create.submit');
    Route::post('user/change', 'Backend\AdminController@user_change_password')->name('user.password.change.submit');
    Route::get('users', 'Backend\AdminController@users');




    //Company
    Route::get('companies', 'Backend\CompanyController@index')->name('companies');
    Route::get('company/create', 'Backend\CompanyController@create')->name('company.create');
    Route::get('company/update/{id}', 'Backend\CompanyController@edit')->name('company.update');
    Route::get('company/profile/{slug}', 'Backend\CompanyController@profile')->name('company.profile');
    Route::post('company/update/{id}', 'Backend\CompanyController@update')->name('company.update.submit');
    Route::get('company/delete/{id}', 'Backend\CompanyController@destroy')->name('company.delete');
    Route::post('company/ban/{id}', 'Backend\AdminController@companyBan')->name('company.ban');


    //Customer
    Route::get('customers', 'Backend\CustomerController@index')->name('customers');
    Route::get('customer/create', 'Backend\CustomerController@create')->name('customer.create');
    Route::get('customer/update/{id}', 'Backend\CustomerController@edit')->name('customer.update');
    Route::post('customer/update/{id}', 'Backend\CustomerController@update')->name('customer.update.submit');
    Route::get('customer/delete/{id}', 'Backend\CustomerController@destroy')->name('customer.delete');
    Route::get('customer/ban', 'Backend\CustomerController@ban');
    Route::get('customer/profile/{username}', 'Backend\CustomerController@profile')->name('customer.profile');




    //Product-Part

    Route::get('products', 'Backend\ProductController@index')->name('products');
    Route::get('product/create', 'Backend\ProductController@create')->name('product.create');
    Route::post('product/create', 'Backend\ProductController@store')->name('product.create.submit');
    Route::get('product/update/{id}', 'Backend\ProductController@edit')->name('product.update');
    Route::post('product/update/{id}', 'Backend\ProductController@update')->name('product.update.submit');
    Route::get('product/show/{slug}', 'Backend\ProductController@show')->name('product.show');
    Route::get('product/delete/{id}', 'Backend\ProductController@destroy')->name('product.delete');
    Route::post('product/image/upload/{id}', 'Backend\ProductController@uploadImage')->name('product.image.store');
    Route::post('product/image/setpriority/{id}', 'Backend\ProductController@setPriority');
    Route::get('product/image/delete/{id}', 'Backend\ProductController@deleteImage')->name('product.image.delete');



        
    //Category
    Route::get('categories', 'Backend\CategoryController@index')->name('categories');
    Route::get('category/create', 'Backend\CategoryController@create')->name('category.create');
    Route::post('category/create', 'Backend\CategoryController@store')->name('category.create.submit');
    Route::get('category/update/{id}', 'Backend\CategoryController@edit')->name('category.update');
    Route::post('category/update/{id}', 'Backend\CategoryController@update')->name('category.update.submit');
    Route::get('category/show/{id}', 'Backend\CategoryController@show')->name('category.show');;
    Route::get('category/delete/{id}', 'Backend\CategoryController@destroy')->name('category.delete');

    


    //Subcategory
    Route::get('subcategories', 'Backend\SubcategoryController@index')->name('subcategories');
    Route::get('subcategory/create', 'Backend\SubcategoryController@create')->name('subcategory.create');
    Route::post('subcategory/create', 'Backend\SubcategoryController@store')->name('subcategory.create.submit');
    Route::get('subcategory/update/{id}', 'Backend\SubcategoryController@edit')->name('subcategory.update');
    Route::post('subcategory/update/{id}', 'Backend\SubcategoryController@update')->name('subcategory.update.submit');
    Route::get('subcategory/show/{id}', 'Backend\SubcategoryController@show')->name('subcategory.show');
    Route::get('subcategory/delete/{id}', 'Backend\SubcategoryController@destroy')->name('subcategory.delete');





    //Division
    Route::get('divisions', 'Backend\DivisionController@index')->name('divisions');
    Route::get('division/create', 'Backend\DivisionController@create')->name('division.create');
    Route::post('division/create', 'Backend\DivisionController@store')->name('division.create.submit');
    Route::get('division/update/{id}', 'Backend\DivisionController@edit')->name('division.update');
    Route::post('division/update/{id}', 'Backend\DivisionController@update')->name('division.update.submit');
    Route::get('division/show/{id}', 'Backend\DivisionController@show')->name('division.show');
    Route::get('division/delete/{id}', 'Backend\DivisionController@destroy')->name('division.delete');




    //District
    Route::get('districts', 'Backend\DistrictController@index')->name('districts');
    Route::get('district/create', 'Backend\DistrictController@create')->name('district.create');;
    Route::post('district/create', 'Backend\DistrictController@store')->name('district.create.submit');
    Route::get('district/update/{id}', 'Backend\DistrictController@edit')->name('district.update');
    Route::post('district/update/{id}', 'Backend\DistrictController@update')->name('district.update.submit');
    Route::get('district/show/{id}', 'Backend\DistrictController@show')->name('district.show');
    Route::get('district/delete/{id}', 'Backend\DistrictController@destroy')->name('district.delete');





    //Upazilla
    Route::get('upazillas', 'Backend\UpazillaController@index')->name('upazillas');
    Route::get('upazilla/create', 'Backend\UpazillaController@create')->name('upazilla.create');
    Route::post('upazilla/create', 'Backend\UpazillaController@store')->name('upazilla.create.submit');
    Route::get('upazilla/update/{id}', 'Backend\UpazillaController@edit')->name('upazilla.update');
    Route::post('upazilla/update/{id}', 'Backend\UpazillaController@update')->name('upazilla.update.submit');
    Route::get('upazilla/show/{id}', 'Backend\UpazillaController@show')->name('upazilla.show');
    Route::get('upazilla/delete/{id}', 'Backend\UpazillaController@destroy')->name('upazilla.delete');





    //Union
    Route::get('unions', 'Backend\UnionController@index')->name('unions');
    Route::get('union/create', 'Backend\UnionController@create')->name('union.create');
    Route::post('union/create', 'Backend\UnionController@store')->name('union.create.submit');
    Route::get('union/update/{id}', 'Backend\UnionController@edit')->name('union.update');
    Route::post('union/update/{id}', 'Backend\UnionController@update')->name('union.update.submit');
    Route::get('union/show/{id}', 'Backend\UnionController@show')->name('union.show');
    Route::get('union/delete/{id}', 'Backend\UnionController@destroy')->name('union.delete');





    //Unit
    Route::get('units', 'Backend\UnitController@index')->name('units');

app/Http/Controllers/Api/CategoryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    // public function __construct()
    // {
    //     $this->middleware('auth:api');
    // }
    public function index()
    {
        try{
            $categories = Category::orderBy('name', 'ASC')->get();
            foreach ($categories as $category) {
                $subcategories = $category->subcategories;
                $products=$category->products;
                if(!is_null($products))
                {
                    foreach ($products as $product) {
                        $product->unit;
                        $product->images;
                        $product->subcategory;
                        $product->company;
                    }
                }
            }
            return response()->json([
                "success"  => true,
                "categories" => $categories,
            ]);
        }
        catch(Exception $e){
            return response()->json([
                'success'=>false,
                'message'=> ''.$e,
            ]);
        }
    }

    public function store(Request  $request)
    {

        $validator = Validator::make($request->all(),[
            'name' => 'sometimes|string',
            'bn_name' => 'nullable|string',
            'description' => 'nullable|string',
            'bn_description' => 'nullable|string',
            'image' => 'nullable|file|image|max:3000',
        ]);
        if ($validator->fails()) {
            return response()->json($validator->errors(), 422);
        }
        try{
            $category= new Category;
            $category->name =$request->name;
            $category->bn_name =$request->bn_name;
            if(is_null($request->description)){
                $category->description ="N/A";
            }else{
                $category->description =$request->description;
            }
            if(is_null($request->bn_description)){
                $category->bn_description ="N/A";
            }else{
                $category->bn_description =$request->bn_description;
            }

            if(is_null($request->image)){
                $category->image="default.png";
            }else if(request()->hasFile('image')){
                $imageName = time().'.'.$request->image->extension();
                $request->image->storeAs('/category',$imageName,'public');
                $category->image=$imageName;
            }

            $slug = Str::slug(str_replace( ' ', '-', $request->name));
            $i = 0;
            while(Category::whereSlug($slug)->exists())
            {
                $i++;
                $slug = $slug ."-". $i;
            }
            $category->slug =$slug;

            $category->save();

            return response()->json([
                "success"  => true,
                "message" => "New Category created!",
                "category" => $category,
            ]);
        }catch(Exception $e){
            return response()->json([
                'success'=>false,
                'message'=> ''.$e,
            ]);
        }
    }

    public function show(Request  $request)
    {
        try{
            $category = Category::find($request->id);
            if(is_null($category))
            return response()->json([
                "success"  => false,
                "message" => "No Category Found!",

            ]);
            $category->subcategories;
            $products= $category->products;
            if(!is_null($products))
                {
                    foreach ($products as $product) {
                        $product->unit;
                        $product->images;
                        $product->subcategory;
                        $product->company;
                    }
                }

            return response()->json([
                "success"  => true,
                "category" => $category,
            ]);
        }
        catch(Exception $e){
            return response()->json([
                'success'=>false,
                'message'=> ''.$e,
            ]);
        }
    }




    public function update(Request $request)
    {
        $validator = Validator::make($request->all(),[
            'name' => 'sometimes|string',
            'bn_name' => 'nullable|string',
            'description' => 'nullable|string',
            'bn_description' => 'nullable|string',
            'image' => 'nullable|file|image|max:3000',
        ]);
        if ($validator->fails()) {
            return response()->json($validator->errors(), 422);
        }
        $category = Category::find($request->id);
        $slug_change=0;
        if(request()->has('name')){
            if($category->name!=$request->name){
                $slug_change=1;
            }
            $category->name =$request->name;
        }
        if(request()->has('bn_name'))
            $category->bn_name =$request->bn_name;
        if(request()->has('description'))
            $category->description =$request->description;
        if(request()->has('bn_description'))
            $category->bn_description =$request->bn_description;
        if(request()->hasFile('image')){
            if(!is_null($category->image) && $category->image !="default.png" &&  $category->image !="default.jpg"){
                $exists = Storage::disk('public')->exists('category/'.$category->image);
                if($exists)
                    Storage::disk('public')->delete('category/'.$category->image);
            }
            $imageName = time().'.'.$request->image->extension();
            $request->image->storeAs('/category',$imageName,'public');
            $category->image=$imageName;
        }

        if($slug_change==1){
            $slug = Str::slug(str_replace( ' ', '-', $request->name));
            $i = 0;
            while(Category::whereSlug($slug)->exists())
            {
                $i++;
                $slug = $slug ."-". $i;
            }
            $category->slug =$slug;
        }
        $category->save();

        return response()->json([
            "success"  => true,
            "message" => "Category has been updated!",
            "category" => $category
        ]);
    }


    public function destroy(Request  $request)
    {
        try{
            $category = Category::find($request->id);
            if(is_null($category))
                return response()->json([
                    "success"  => false,
                    "message" => "No Category Found!",
                ]);

            if (!is_null($category->image) && $category->image !="default.png" &&  $category->image !="default.jpg") {
                $exists = Storage::disk('public')->exists('category/'.$category->image);
                if($exists)
                    Storage::disk('public')->delete('category/'.$category->image);
            }
            $category->delete();
            return response()->json([
                "success"  => true,
                "message" => "Category has been deleted!",
            ]);
        }
        catch(Exception $e){
            return response()->json([
                'success'=>false,
                'message'=> ''.$e,
            ]);
        }
    }
}

resources/views/backend/category/add.blade.php
@extends('backend.layouts.master')
@section('title','Category')

@section('contents')
@include('backend.layouts.sidebar')
  <section class="container-fluid">
    <section class="row justify-content-center">
      <section class="col-12 col-sm-6 col-md-3">
        <div class="form-container">
          <div class="container">

            @if(Session::has('success'))

              <div class="alert alert-success alert-block">
                  <button type="button" class="close" data-dismiss="alert">
                      x
                  </button>
                  <strong>
                    {!! session('success')!!}   @php Session::forget('success') @endphp &nbsp;&nbsp; 
                    @if(!is_null($category)) <a href="{{route('admin.category.update',$category)}}">Edit</a> @endif
                  </strong>
              </div>
            @endif
            @if(Session::has('failed'))
    
              <div class="alert alert-error alert-block">
                  <button type="button" class="close" data-dismiss="alert">
                      x
                  </button>
                  <strong>
                      {!! session('failed') !!}
                  </strong>
              </div>
      
            @endif
            <div class="text-center">
              <h2>Add Category</h2>
            </div>
          </div>

            <form  method="POST" action="{{ route('admin.category.create.submit') }}" enctype="multipart/form-data" novalidate="novalidate">
              @csrf
              <div class="form-group">
                <label for="Name">Name</label>
                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                 id="exampleFormControlInput1" placeholder="Electronics">
                @error('name')
                  <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">
                      x
                    </button>
                    <strong>
                        {!! $message !!}
                    </strong>
                  </div>
                @enderror
              </div>

              <div class="form-group">
                <label for="exampleFormControlInput1">Name in Bangla</label>
                <input type="text" name="bn_name" class="form-control  @error('bn_name') is-invalid @enderror" id="exampleFormControlInput1" placeholder="">
                @error('bn_name')
                  <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">
                      x
                    </button>
                    <strong>
                        {!! $message !!}
                    </strong>
                  </div>
               @enderror
              </div>

              <div class="form-group">
                <label for="exampleFormControlFile1">Upload Image</label>
                <input type="file" name="image" class="form-control @error('image') is-invalid @enderror" id="image"  accept="image/*" onchange="showImgPreview(event);">
                @error('image')
                  <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">
                      x
                    </button>
                    <strong>
                        {!! $message !!}
                    </strong>
                  </div>
                @enderror
                <div class="preview">
                  <img id="img-preview">
                </div>
              </div>
              
              <div class="form-group">
                <label for="exampleFormControlTextarea1">Description</label>
                <textarea class="form-control @error('description') is-invalid @enderror" name="description" id="exampleFormControlTextarea1" rows="3" placeholder="Write something about the Category..."></textarea>
                @error('description')
                  <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">
                      x
                    </button>
                    <strong>
                        {!! $message !!}
                    </strong>
                  </div>
                @enderror
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">Description in Bangla</label>
                <textarea class="form-control @error('bn_description') is-invalid @enderror" name="bn_description" id="exampleFormControlTextarea1" rows="3" placeholder="Write something about the Category..."></textarea>
                @error('bn_description')
                  <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">
                      x
                    </button>
                    <strong>
                        {!! $message !!}
                    </strong>
                  </div>
                @enderror
              </div>

              <center>
                <input type="submit" class="btn btn-success btn-block" value="Submit">
                <a href="#" class="btn btn-primary btn-block">Add More</a>
              </center>
            </form>
          </div>
        </section>
      </section>
    </section>
    @endsection

resources/views/backend/category/edit.blade.php
@extends('backend.layouts.master')
@section('title','Category')

@section('contents')
@include('backend.layouts.sidebar')
  <section class="container-fluid">
    <section class="row justify-content-center">
      <section class="col-12 col-sm-6 col-md-3">
        <div class="form-container">
          <div class="container">

            @if(Session::has('success'))
              <div class="alert alert-success alert-block">
                  <button type="button" class="close" data-dismiss="alert">
                      x
                  </button>
                  <strong>
                      {!! session('success') !!}
                  </strong>
              </div>
            @endif
            @if(Session::has('failed'))  
              <div class="alert alert-error alert-block">
                  <button type="button" class="close" data-dismiss="alert">
                      x
                  </button>
                  <strong>
                      {!! session('failed') !!}
                  </strong>
              </div>
            @endif
            <div class="text-center">
              <h2>Edit Category</h2>
            </div>
          </div>

            <form  method="POST" action="{{ route('admin.category.update.submit',$category->id) }}" enctype="multipart/form-data" novalidate="novalidate">
              @csrf
              <div class="form-group">
                <label for="Name">Name</label>
              <input type="text" name="name" value="{{$category->name}}" class="form-control @error('name') is-invalid @enderror"
                 id="exampleFormControlInput1" placeholder="Electronics">
                @error('name')
                  <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">
                      x
                    </button>
                    <strong>
                        {!! $message !!}
                    </strong>
                  </div>
                @enderror
              </div>

              <div class="form-group">
                <label for="exampleFormControlInput1">Name in Bangla</label>
                <input type="text" name="bn_name" value="{{$category->bn_name}}" class="form-control  @error('bn_name') is-invalid @enderror" id="exampleFormControlInput1" placeholder="">
                @error('bn_name')
                  <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">
                      x
                    </button>
                    <strong>
                        {!! $message !!}
                    </strong>
                  </div>
               @enderror
              </div>

              <div class="form-group">
                <label for="Category Image">Category Image :</label>
                <div class="preview">
                  <img style="display:block; max-width: 200px; padding-left: 10px;padding-bottom: 3px; margin-left: 60px;" src="{{ asset('storage/category')}}/{{$category->image}}" >
                </div>
                <input type="file" name="image" class="form-control @error('image') is-invalid @enderror" id="image" accept="image/*" onchange="showImgPreview(event);">
                @error('image')
                  <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">
                      x
                    </button>
                    <strong>
                        {!! $message !!}
                    </strong>
                  </div>
                @enderror
                <div class="preview">
                  <img id="img-preview">
                </div>
              </div>
              
              <div class="form-group">
                <label for="exampleFormControlTextarea1">Description</label>
                <textarea class="form-control @error('description') is-invalid @enderror" 
                name="description" id="exampleFormControlTextarea1" rows="3" 
                placeholder="Write something about the Category...">{!!$category->description!!}</textarea>
                @error('description')
                  <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">
                      x
                    </button>
                    <strong>
                        {!! $message !!}
                    </strong>
                  </div>
                @enderror
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">Description in Bangla</label>
                <textarea class="form-control @error('bn_description') is-invalid @enderror" name="bn_description" id="exampleFormControlTextarea1" rows="3" placeholder="Write something about the Category...">{!!$category->bn_description!!}</textarea>
                @error('bn_description')
                  <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">
                      x
                    </button>
                    <strong>
                        {!! $message !!}
                    </strong>
                  </div>
                @enderror
              </div>

              <center>
                <input type="submit" class="btn btn-success btn-block" value="Update">
                <a href="#" class="btn btn-primary btn-block">Add More</a>
              </center>
            </form>
          </div>
        </section>
      </section>
    </section>
    @endsection

resources/views/backend/category/index.blade.php
@extends('backend.layouts.master')
@section('title','Categories')

@section('contents')
@include('backend.layouts.sidebar')
<div class="content">
    <center>
        <div class="heading">
            <h4>All the Categories are here</h4>
        </div>
    </center>
    <table id="dataTable" class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Name in Bangla</th>
          <th scope="col">Description</th>
          <th scope="col">Description in Bangla</th>
          <th scope="col">Image</th>
          <th scope="col">Edit</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
          @foreach (App\Models\Category::latest()->get() as $category)
            <tr>
                <th scope="row">{{$loop->index+1}}</th>
                <td>{{$category->name}}</td>
                <td>{{$category->bn_name}}</td>

                <td>{!!strlen($category->description) > 100 ? substr($category->description,0,100)." .....": $category->description!!}</td>
                <td>{!!strlen($category->bn_description) > 100 ? substr($category->bn_description,0,100)." ...": $category->bn_description!!}</td>
                <td><img src="{{ asset('storage/category')}}/{{$category->image}}"
                    style="width:30px;" class="user-image" alt="Category Image"></td>
                <td><a href="{{route('admin.category.update',$category->id)}}">Edit</a></td>
                <td><a class="delete" data-confirm="Are you sure to delete this item?"
                    href="{{route('admin.category.delete',$category->id)}}">Delete</a></td>
            </tr>
          @endforeach
      </tbody>
    </table>
    {{-- {!! App\Models\Category::categoies()->render() !!} --}}
</div>


<script src="{{ asset('js/backend/jquery.min.js')}}"></script>
<script>
    var deleteLinks = document.querySelectorAll('.delete');

    for (var i = 0; i < deleteLinks.length; i++) {
        deleteLinks[i].addEventListener('click', function(event) {
            event.preventDefault();

            var choice = confirm(this.getAttribute('data-confirm'));

            if (choice) {
                window.location.href = this.getAttribute('href');
            }
        });
    }
</script>
@endsection