routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear-cache', function() {
    $run = Artisan::call('config:clear');
    $run = Artisan::call('cache:clear');
    $run = Artisan::call('config:cache');
    return 'FINISHED';  
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



/*
|--------------------------------------------------------------------------
|-------------------------- ---Admin Routes--- ----------------------------
|--------------------------------------------------------------------------
*/


//Auth
Route::group( ['prefix' => 'admin', 'as' => 'admin.'], function() {

    //Authorization
    Route::get('/login','Backend\Auth\AdminAuthController@showLoginForm')->name('login');
    
    Route::post('/login', 'Backend\Auth\AdminAuthController@login')->name('login.submit');
    Route::get('logout/', 'Backend\Auth\AdminAuthController@logout')->name('logout');

    // Password Reset
    Route::get('/password/reset','Backend\Auth\AdminAuthController@showLinkRequestForm')
    ->name('password.request');
    Route::post('/password/email','Backend\Auth\ResetPasswordController@sendResetLinkEmail')
    ->name('password.email');

    Route::get('/password/reset/{token}', 'Backend\Auth\ResetPasswordController@showResetForm')
    ->name('password.reset');
    Route::post('/password/reset', 'Backend\Auth\ResetPasswordController@reset')
        ->name('password.update');


    //Dashboard
    Route::get('/', 'Backend\AdminController@index')->name('dashboard');




    // ********Functionalities*********

    //Admin
    Route::get('admin/create', 'Backend\AdminController@createAdmin')->name('admin.create');
    Route::post('admin/create', 'Backend\AdminController@storeAdmin')->name('admin.create.submit');
    Route::post('admin/ban', 'Backend\AdminController@adminBan');
    Route::get('admin/update/{id}', 'Backend\AdminController@editAdmin')->name('admin.update');
    Route::post('admin/update/{id}', 'Backend\AdminController@updateAdmin')->name('admin.update.submit');
    Route::get('admins', 'Backend\AdminController@admins')->name('admins');
    Route::get('profile/{username}', 'Backend\AdminController@profile')->name('profile');
    Route::get('profile', 'Backend\AdminController@show')->name('profile.own');
    Route::post('profile/update', 'Backend\AdminController@update');
    Route::get('admin/delete/{id}', 'Backend\AdminController@destroy')->name('admin.delete');
   


    //User
    Route::post('user/create', 'Backend\AdminController@userCreate')->name('user.create.submit');
    Route::post('user/change', 'Backend\AdminController@user_change_password')->name('user.password.change.submit');
    Route::get('users', 'Backend\AdminController@users');




    //Company
    Route::get('companies', 'Backend\CompanyController@index')->name('companies');
    Route::get('company/create', 'Backend\CompanyController@create')->name('company.create');
    Route::get('company/update/{id}', 'Backend\CompanyController@edit')->name('company.update');
    Route::get('company/profile/{slug}', 'Backend\CompanyController@profile')->name('company.profile');
    Route::post('company/update/{id}', 'Backend\CompanyController@update')->name('company.update.submit');
    Route::get('company/delete/{id}', 'Backend\CompanyController@destroy')->name('company.delete');
    Route::post('company/ban/{id}', 'Backend\AdminController@companyBan')->name('company.ban');


    //Customer
    Route::get('customers', 'Backend\CustomerController@index')->name('customers');
    Route::get('customer/create', 'Backend\CustomerController@create')->name('customer.create');
    Route::get('customer/update/{id}', 'Backend\CustomerController@edit')->name('customer.update');
    Route::post('customer/update/{id}', 'Backend\CustomerController@update')->name('customer.update.submit');
    Route::get('customer/delete/{id}', 'Backend\CustomerController@destroy')->name('customer.delete');
    Route::get('customer/ban', 'Backend\CustomerController@ban');
    Route::get('customer/profile/{username}', 'Backend\CustomerController@profile')->name('customer.profile');




    //Product-Part

    Route::get('products', 'Backend\ProductController@index')->name('products');
    Route::get('product/create', 'Backend\ProductController@create')->name('product.create');
    Route::post('product/create', 'Backend\ProductController@store')->name('product.create.submit');
    Route::get('product/update/{id}', 'Backend\ProductController@edit')->name('product.update');
    Route::post('product/update/{id}', 'Backend\ProductController@update')->name('product.update.submit');
    Route::get('product/show/{slug}', 'Backend\ProductController@show')->name('product.show');
    Route::get('product/delete/{id}', 'Backend\ProductController@destroy')->name('product.delete');
    Route::post('product/image/upload/{id}', 'Backend\ProductController@uploadImage')->name('product.image.store');
    Route::post('product/image/setpriority/{id}', 'Backend\ProductController@setPriority');
    Route::get('product/image/delete/{id}', 'Backend\ProductController@deleteImage')->name('product.image.delete');



        
    //Category
    Route::get('categories', 'Backend\CategoryController@index')->name('categories');
    Route::get('category/create', 'Backend\CategoryController@create')->name('category.create');
    Route::post('category/create', 'Backend\CategoryController@store')->name('category.create.submit');
    Route::get('category/update/{id}', 'Backend\CategoryController@edit')->name('category.update');
    Route::post('category/update/{id}', 'Backend\CategoryController@update')->name('category.update.submit');
    Route::get('category/show/{id}', 'Backend\CategoryController@show')->name('category.show');;
    Route::get('category/delete/{id}', 'Backend\CategoryController@destroy')->name('category.delete');

    


    //Subcategory
    Route::get('subcategories', 'Backend\SubcategoryController@index')->name('subcategories');
    Route::get('subcategory/create', 'Backend\SubcategoryController@create')->name('subcategory.create');
    Route::post('subcategory/create', 'Backend\SubcategoryController@store')->name('subcategory.create.submit');
    Route::get('subcategory/update/{id}', 'Backend\SubcategoryController@edit')->name('subcategory.update');
    Route::post('subcategory/update/{id}', 'Backend\SubcategoryController@update')->name('subcategory.update.submit');
    Route::get('subcategory/show/{id}', 'Backend\SubcategoryController@show')->name('subcategory.show');
    Route::get('subcategory/delete/{id}', 'Backend\SubcategoryController@destroy')->name('subcategory.delete');





    //Division
    Route::get('divisions', 'Backend\DivisionController@index')->name('divisions');
    Route::get('division/create', 'Backend\DivisionController@create')->name('division.create');
    Route::post('division/create', 'Backend\DivisionController@store')->name('division.create.submit');
    Route::get('division/update/{id}', 'Backend\DivisionController@edit')->name('division.update');
    Route::post('division/update/{id}', 'Backend\DivisionController@update')->name('division.update.submit');
    Route::get('division/show/{id}', 'Backend\DivisionController@show')->name('division.show');
    Route::get('division/delete/{id}', 'Backend\DivisionController@destroy')->name('division.delete');




    //District
    Route::get('districts', 'Backend\DistrictController@index')->name('districts');
    Route::get('district/create', 'Backend\DistrictController@create')->name('district.create');;
    Route::post('district/create', 'Backend\DistrictController@store')->name('district.create.submit');
    Route::get('district/update/{id}', 'Backend\DistrictController@edit')->name('district.update');
    Route::post('district/update/{id}', 'Backend\DistrictController@update')->name('district.update.submit');
    Route::get('district/show/{id}', 'Backend\DistrictController@show')->name('district.show');
    Route::get('district/delete/{id}', 'Backend\DistrictController@destroy')->name('district.delete');





    //Upazilla
    Route::get('upazillas', 'Backend\UpazillaController@index')->name('upazillas');
    Route::get('upazilla/create', 'Backend\UpazillaController@create')->name('upazilla.create');
    Route::post('upazilla/create', 'Backend\UpazillaController@store')->name('upazilla.create.submit');
    Route::get('upazilla/update/{id}', 'Backend\UpazillaController@edit')->name('upazilla.update');
    Route::post('upazilla/update/{id}', 'Backend\UpazillaController@update')->name('upazilla.update.submit');
    Route::get('upazilla/show/{id}', 'Backend\UpazillaController@show')->name('upazilla.show');
    Route::get('upazilla/delete/{id}', 'Backend\UpazillaController@destroy')->name('upazilla.delete');





    //Union
    Route::get('unions', 'Backend\UnionController@index')->name('unions');
    Route::get('union/create', 'Backend\UnionController@create')->name('union.create');
    Route::post('union/create', 'Backend\UnionController@store')->name('union.create.submit');
    Route::get('union/update/{id}', 'Backend\UnionController@edit')->name('union.update');
    Route::post('union/update/{id}', 'Backend\UnionController@update')->name('union.update.submit');
    Route::get('union/show/{id}', 'Backend\UnionController@show')->name('union.show');
    Route::get('union/delete/{id}', 'Backend\UnionController@destroy')->name('union.delete');





    //Unit
    Route::get('units', 'Backend\UnitController@index')->name('units');

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Log;
use Auth;
class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index()
    {
        // $slug=Category::slugComplete();
        // dd($slug);
        return view('backend.category.index');
    }

    public function create(){
        return view('backend.category.add');
    }

    public function store(Request  $request)
    {

        $this->validate($request,[
            'name' => 'sometimes|string',
            'bn_name' => 'nullable|string',
            'description' => 'nullable|string',
            'bn_description' => 'nullable|string',
            'image' => 'nullable|file|image|max:3000',
        ]);
        try{
            $category= new Category;
            $category->name =$request->name;
            $category->bn_name =$request->bn_name;
            if(is_null($request->description)){
                $category->description ="N/A";
            }else{
                $category->description =$request->description;
            }
            if(is_null($request->bn_description)){
                $category->bn_description ="N/A";
            }else{
                $category->bn_description =$request->bn_description;
            }
            $category->admin_id=Auth::guard('admin')->user()->id;
            if(is_null($request->image)){
                $category->image="default.png";
            }else if(request()->hasFile('image')){
                $imageName = time().'.'.$request->image->extension();
                $request->image->storeAs('/category',$imageName,'public');
                $category->image=$imageName;
            }

            $slug = Str::slug(str_replace( ' ', '-', $request->name));
            $i = 0;
            while(Category::whereSlug($slug)->exists())
            {
                $i++;
                $slug = $slug ."-". $i;
            }
            $category->slug =$slug;

            $category->save();

            session()->flash('success', 'New Category Added!!');
            return view('backend.category.add')->with('category',$category->id);
        }catch(Exception $e){
            session()->flash('failed', 'Error occured! --'.$e);
            return redirect()->route('admin.category.create');
        }
    }

    public function show(Request  $request)
    {
        try{
            $category = Category::find($request->id);
            if(is_null($category))
            return response()->json([
                "sucess"  => false,
                "message" => "No Category Found!",

            ]);

            return response()->json([
                "sucess"  => true,
                "category" => $category,
            ]);
        }
        catch(Exception $e){
            return response()->json([
                'success'=>false,
                'message'=> ''.$e,
            ]);
        }
    }

    public function edit($id){
        $category= Category::find($id);
        return view('backend.category.edit')->with('category',$category);
    }



    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'sometimes|string',
            'bn_name' => 'nullable|string',
            'description' => 'nullable|string',
            'bn_description' => 'nullable|string',
            'image' => 'nullable|file|image|max:3000',
        ]);
        $category = Category::find($id);
        $slug_change=0;
        if($category->name!=$request->name){
            $slug_change=1;
        }
        $category->name =$request->name;
        $category->bn_name =$request->bn_name;
        $category->description =$request->description;
        $category->bn_description =$request->bn_description;
        if(request()->hasFile('image')){
            if(!is_null($category->image) && $category->image !="default.png" &&  $category->image !="default.jpg"){
                $exists = Storage::disk('public')->exists('category/'.$category->image);
                if($exists)
                    Storage::disk('public')->delete('category/'.$category->image);
            }
            $imageName = time().'.'.$request->image->extension();
            $request->image->storeAs('/category',$imageName,'public');
            $category->image=$imageName;
        }

        if($slug_change==1){
            $slug = Str::slug(str_replace( ' ', '-', $request->name));
            $i = 0;
            while(Category::whereSlug($slug)->exists())
            {
                $i++;
                $slug = $slug ."-". $i;
            }
            $category->slug =$slug;
        }
        $category->save();

        session()->flash('success', 'Category has been updated!!');
        return redirect()->route('admin.category.update',$category->id);
    }


    public function destroy($id)
    {
        try{
            $category = Category::find($id);
            if(is_null($category)){
            session()->flash('failed', 'No category found !!!');
            return redirect()->route('admin.categories');
        }
            if (!is_null($category->image) && $category->image !="default.png" &&  $category->image !="default.jpg") {
                $exists = Storage::disk('public')->exists('category/'.$category->image);
                if($exists)
                   Storage::disk('public')->delete('category/'.$category->image);
            }
            $category->delete();
            session()->flash('success', 'A Category has been Deleted!!');
            return redirect()->route('admin.categories');
        }catch(Exception $e){
            session()->flash('failed', 'Error occured! --'.$e);
            return redirect()->route('admin.dashboard');
        }
    }
}

resources/views/backend/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Egol.com.bd || @yield('title')</title>
	<link rel="stylesheet" href="{{ asset('css/backend/bootstrap.css') }}?ver=1.1">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/backend/global.css') }}?ver=1.1">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/backend/profile.css') }}?ver=1.1">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/backend/slider.css') }}?ver=1.1">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/backend/product.css') }}?ver=1.1">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/backend/sidebar.css') }}?ver=1.1">
	<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
		<!-- Datatables css-->
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css"/>
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/autofill/2.3.5/css/autoFill.bootstrap4.css"/>
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedcolumns/3.3.1/css/fixedColumns.bootstrap4.min.css"/>
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.5/css/responsive.bootstrap4.min.css"/>
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/scroller/2.0.2/css/scroller.bootstrap4.min.css"/>
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/searchpanes/1.1.1/css/searchPanes.bootstrap4.min.css"/>
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.3.1/css/select.bootstrap4.min.css"/>

	{{-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"/> --}}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/js/all.min.js"></script>

	<!-- Select2 css-->
	<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />

	<style>.select2-container, .select2-dropdown, .select2-search, .select2-results {
		-webkit-transition: none !important;
		-moz-transition: none !important;
		-ms-transition: none !important;
		-o-transition: none !important;
		transition: none !important;
	}
	</style>


	<script src="{{ asset('js/backend/jquery.min.js') }}?ver=1.1" ></script>
	<script src="{{ asset('js/server.js') }}?ver=1.1" ></script>


	<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
	{{-- <script src="{{ asset('js/backend/jquery-3.3.1.min.js')}}"></script> --}}
</head>
<body>

	<input type="checkbox" id="check">

	<header>
		<label for="check">
			<i class="fa fa-bars" id="sidebar-btn"></i>
		</label>
		<div class="left-area">
			<h3>Egol<span>.com.bd</span></h3>
		</div>

		<div class="right-area">

			<a href="{{route('admin.logout')}}" class="btn btn-primary btn-sm">Logout</a>

			<div class="user" onclick="window.location.href='{{route('admin.profile.own')}}'" style="cursor: pointer">
				<img src="{{ asset('storage/admin')}}/{{Auth::guard('admin')->user()->image}}" class="user-image" alt=" ">
			<h4 class="user-name">{{Auth::guard('admin')->user()->username}}</h4>
			</div>

		</div>
	</header>


	@yield('contents')
	{{-- image preview --}}
	<script>
		function showImgPreview(event){
		if (event.target.files.length>0) {
			var src = URL.createObjectURL(event.target.files[0]);
			var preview = document.getElementById("img-preview");
			preview.src = src;
			preview.style.display = "block";
			preview.style.maxWidth= "200px";
			preview.style.marginLeft= "60px";
			preview.style.marginTop= "5px";
			preview.style.paddingLeft= "10px";
		}
	}
	</script>


			<!-- Datatables js-->


<script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/autofill/2.3.5/js/dataTables.autoFill.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/autofill/2.3.5/js/autoFill.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/fixedcolumns/3.3.1/js/dataTables.fixedColumns.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.5/js/dataTables.responsive.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.5/js/responsive.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/scroller/2.0.2/js/dataTables.scroller.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/searchpanes/1.1.1/js/dataTables.searchPanes.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/searchpanes/1.1.1/js/searchPanes.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/select/1.3.1/js/dataTables.select.min.js"></script>


<script type="text/javascript">
	$(document).ready(function() {
		$('#dataTable').DataTable({
			responsive: true,
			'aoColumnDefs': [{
        'bSortable': false,
        'aTargets': [-1,-2, -3] /* 1st one, start by the right */
    }]
		});
	});
</script>
	<!-- Select2 JS-->
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script>
	$(document).ready(function() {
	  $('.select2').select2({
		theme: "classic"
		//allowClear: true
	});

  });
</script>



<!-- JS, Popper.js, and jQuery -->

	{{-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> --}}

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
	<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

</body>
</html>

resources/views/backend/layouts/sidebar.blade.php
<div class="sidebar">

    <ul class="list-unstyled components">
        <li class="active"> 
            <a href="{{route('admin.dashboard')}}"><i class="fas fa-desktop"></i><span>Dashboard</span></a>
        </li>


        <li>
            <a href="#company" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="far fa-building"></i><span>Companies</span></a>
            <ul class="collapse list-unstyled" id="company">
                <li>
                    <a href="{{route('admin.company.create')}}"><i class="fas fa-plus"></i><span>Add New</span></a>
                </li>

                <li>
                    <a href="{{route('admin.companies')}}"><i class="fas fa-eye"></i><span>View</span></a>
                </li>
            </ul>
        </li>

        <li>
            <a href="#customer" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-users"></i><span>Customers</span></a>
            
            <ul class="collapse list-unstyled" id="customer">
                <li>
                    <a href="{{route('admin.customer.create')}}"><i class="fas fa-plus"></i><span>Add New</span></a>
                </li>
                <li>
                    <a href="{{route('admin.customers')}}"><i class="fas fa-eye"></i><span>View</span></a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#admin" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-user-shield"></i><span>Admins</span></a>
            
            <ul class="collapse list-unstyled" id="admin">
                <li>
                    <a href="{{route('admin.admin.create')}}"><i class="fas fa-plus"></i><span>Add New</span></a>
                </li>

                <li>
                    <a href="{{route('admin.admins')}}"><i class="fas fa-eye"></i><span>View</span></a>
                </li>
            </ul>
        </li>

        <li>
            <a href="#product" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-shopping-cart"></i><span>Products</a>
            <ul class="collapse list-unstyled" id="product">
                <li>
                    <a href="{{route('admin.product.create')}}"><i class="fas fa-plus"></i><span>Add New</span></a>
                </li>

                <li>
                    <a href="{{route('admin.products')}}"><i class="fas fa-eye"></i><span>View</span></a>
                </li>
            </ul>
        </li>

        <li>
            <a href="#category" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-align-left"></i><span>Categories</a>
            <ul class="collapse list-unstyled" id="category">
                <li>
                    <a href="{{route('admin.category.create')}}"><i class="fas fa-plus"></i><span>Add New</span></a>
                </li>

                <li>
                    <a href="{{route('admin.categories')}}"><i class="fas fa-eye"></i><span>View</span></a>
                </li>
            </ul>
        </li>

        <li>
            <a href="#subcategory" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-align-right"></i><span>Sub-Categories</span></a>
            <ul class="collapse list-unstyled" id="subcategory">
                <li>
                    <a href="{{route('admin.subcategory.create')}}"><i class="fas fa-plus"></i><span>Add New</span></a>
                </li>

                <li>
                    <a href="{{route('admin.subcategories')}}"><i class="fas fa-eye"></i><span>View</span></a>
                </li>
            </ul>
        </li>

        <li>
            <a href="#unit" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fab fa-buromobelexperte"></i><span>Units</span></a>
            <ul class="collapse list-unstyled" id="unit">
                <li>
                    <a href="{{route('admin.unit.create')}}"><i class="fas fa-plus"></i><span>Add New</span></a>
                </li>

                <li>
                    <a href="{{route('admin.units')}}"><i class="fas fa-eye"></i><span>View</span></a>
                </li>
            </ul>
        </li>

        <li>
            <a href="#place" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-globe-europe"></i><span>Places</span></a>
            <ul class="collapse list-unstyled" id="place">
                <li>
                    <a href="#division" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-map-marker"></i><span>Divisions</a>
                    <ul class="collapse list-unstyled" id="division">
                        <li>
                            <a href="{{route('admin.division.create')}}"><i class="fas fa-plus"></i><span>Add New</span></a>
                        </li>

                        <li>
                            <a href="{{route('admin.divisions')}}"><i class="fas fa-eye"></i><span>View</span></a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="#district" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-map-marker"></i><span>Districts</a>
                    <ul class="collapse list-unstyled" id="district">
                        <li>
                            <a href="{{route('admin.district.create')}}"><i class="fas fa-plus"></i><span>Add New</span></a>
                        </li>

                        <li>
                            <a href="{{route('admin.districts')}}"><i class="fas fa-eye"></i><span>View</span></a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="#upazila" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-map-marker"></i><span>Upazillas</span></a>
                    <ul class="collapse list-unstyled" id="upazila">
                        <li>
                            <a href="{{route('admin.upazilla.create')}}"><i class="fas fa-plus"></i><span>Add New</span></a>
                        </li>

                        <li>
                            <a href="{{route('admin.upazillas')}}"><i class="fas fa-eye"></i><span>View</span></a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="#union" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-map-marker"></i><span>Unions</a>
                    <ul class="collapse list-unstyled" id="union">
                        <li>
                            <a href="{{route('admin.union.create')}}"><i class="fas fa-plus"></i><span>Add New</span></a>
                        </li>

                        <li>
                            <a href="{{route('admin.unions')}}"><i class="fas fa-eye"></i><span>View</span></a>
                        </li>
                    </ul>
                </li>
        
            </ul>
        </li>
    </ul>
</div>
<script>
    $(document).ready(function(){
      $('ul li a').click(function(){
    $('li a').removeClass("active");
    $(this).addClass("active");
    });
    });
</script>